server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: identity

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}?stringtype=unspecified

  web:
    error:
      include-message: always
      include-binding-errors: always

  jackson:
    time-zone: UTC
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST}

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

security:
  rsa:
    private-key: classpath:certs/private-key.pem
    public-key: classpath:certs/public-key.pem

  token:
    expiration-time: 24
    time-unit: HOURS

kafka:
  topics:
    user-commands-topic: user-commands
